Traceback (most recent call last):
  File "../code/sensitivity_num_features.py", line 23, in <module>
    {feature:feature_map[feature]},
KeyError: '15'
